### 오늘의 공부

프로젝트를 정리하면서 에러 처리 코드가 부족한 것을 발견하여 정리하는 동안, 에러 처리 구문에 대한 복습을 하게 되었다.<br>


- 오류 타입으로 열거형(Enumeration)을 정의하는 것은 프로그래밍에서 일반적으로
사용되는 방법 중 하나이다.<br>
열거형을 사용하여 다양한 오류 상황을 나타내고, 각각의 상황에 대한 처리를 보다 구조화하고 명확하게 할 수 있었다.<br>

```swift
enum ValidationError: Error {
    case tooShort
    case tooLong
    case cancel
    case noAuthority
}
```
ValidationError 이름의 열거형을 정의하고, 이 열거형이 Error 프로토콜을 채택하도록 만들었다.

```swift
func someFunction() throws {
    // 오류가 발생할 수 있는 코드
    if someCondition {
        throw ValidationError.tooShort
    } else {
        throw ValidationError.tooLong
    }
}

do {
    try someFunction()
} catch ValidationError.cancel {
   
} catch ValidationError.noAuthority {
   
} catch {
    // 기타 다른 오류 처리
}
```
이와 같이 정의된 열거형은 앱에서 발생하는 다양한 오류를 명확하게 표현하고 처리할 수 있었다.

```swift
extension ValidationError {
    var errorDescription: String? {
        switch self {
        case .tooShort:
            return "Too Short"
        case .tooLong:
            return "Need few Line"
        case .cancel:
            return "Nothing Happen"
        case .noAuthority:
            return "User Don't have Authority"
        }
    }
}
```

- try-catch 문은 스위프트에서 오류 처리를 위해 사용되는 구문이다. throws 키워드와 함께 사용되며, 함수나 메서드 내에서 오류가 발생할 수 있는 코드 블록을 try로 감싸고, catch 블록을 통해 오류를 처리한다.<br>

```swift
do {
    // 오류가 발생할 수 있는 코드 블록
    try 오류가 발생할 수 있는 함수 또는 메서드 호출
} catch 오류 타입 { 
    // 오류에 대한 처리
}
```
만약 오류가 발생하지 않으면 catch 블록은 실행되지 않는다.<br>

- 만약에 여러개의 catch 블록이 있다면?

먼저 선언된 오류 타입에 대한 catch 블록부터 순차적으로 검사된다.<br>
따라서 보다 구체적인 오류 타입을 먼저 처리하고, 나중에 보다 일반적인 오류 타입을
처리하는 것이 권장한다.<br>
